### ISSUE TITLE
Is username required for account-only registration?

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#499]

**Comment by AmirSavand** [comment]
Having it is not bad @Alir3z4 
If we remove it user will have to set it later...

**Comment by Alir3z4** [comment]
Nope, the field is not even there.

On 18 Jun 2017 16:53, "Amir Mehdi Savand" <notifications@github.com> wrote:

Having it is not bad @Alir3z4 <https://github.com/alir3z4>
If we remove it user will have to set it later...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SavandBros/gonevis-dash/issues/499#issuecomment-309276033>,
or mute the thread

**Comment by AmirSavand** [comment]
It's there, anyway it better be.
