### ISSUE TITLE
Should we consider a lighter design/CSS framework ?

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#880]
Currently we're using Bootstrap with the help of Angular Bootstrap UI for easier integration.
As far as I know, we're using it mostly for it grid system and not much else.

I am bringing up this discussion since our main UI framework need to be upgraded and going from bootstrap to bootstrap 4 would require lots of modifications etc.

I have found https://purecss.io/ to be something nice and easy to work with and it's very small. (~4 KB **gzipped**).

Please share your thoughts here.

**Comment by Alir3z4** [comment]
I'm not in favor of using bootstrap or even upgrading it, I am more happy to stay on the same version than put time on upgrading to bootstrap 4. If we're going to upgrade that time better to be spent on dropping it completely, however that depends on how much we depend on it.

**Comment by AmirSavand** [comment]
@Alir3z4 since out sidebar update, the style has changed a lot, we're using bootstrap as our base style and use it's component a lot.

We can update our design again, the framework is just the skeleton.

If you look at our get-starter page or main view it looks nothing like bootstrap, however if you have any design ideas please share your ideas.

About upgrading, we don't have to upgrade now, we can keep it on hold as long as there are other important stuff to do.

I want bootstarp 4 because of all the fixes it contains and browser compatibility  issues.

You should check the difference between bootstrap 3 and 4.

**Comment by AmirSavand** [comment]
@ArsalanSavand if there's any UX issues, you should open an issue for each of them.

**Comment by Alir3z4** [comment]
> It's all in vendor and cached if you're talking about size.

Well, size matters here and it's pretty big.
Although I also don't like the idea of rewriting and putting lots of time into that.

In that case, I'll say we stay on bootstrap and continue what we are using.
To continue optimizing, we can work on https://github.com/SavandBros/gonevis-dash/issues/882 to make it lighter.

Thanks for the feedbacks

**Comment by AmirSavand** [comment]
Cool
