### ISSUE TITLE
Add a list of icons for user to choose for navigation.

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#986]
Users don't have any idea about FontAwesome Icons and their names.
We should create a service that contains all the FontAwesome icons, that user can see and choose his/her desire one.

**Comment by Alir3z4** [comment]
FontAwesome itself uses algolia to make the search happen.
For example on https://fontawesome.com/v4.7.0/icons/

I'm not sure how we're going to make that happen for them.
One way would be to keep all the front-awesome icons in one a json file and load them via URL (like what we do for tags auto-complete) and then use a auto-complete and let user the pick from the result.

The actual problem is, how we're going to get the list of icons.

**Comment by AmirSavand** [comment]
We get the list of icons from the list of icons.

This is a piece of cake task.

**Comment by Alir3z4** [comment]
Ok that's some supernatural move right there, I call UFO!

where is that list ?
